-- we don't know how to generate schema BIGSTOMACH (class Schema) :(
create table "Users"
(
	"UserId" NUMBER(19) generated by default on null as identity
		primary key,
	"UserName" NVARCHAR2(20) not null
		unique,
	"Password" NVARCHAR2(100) not null,
	"UserType" NUMBER(1) not null,
	"ImgUrl" NVARCHAR2(2000) default ('https://tongji4m3.oss-cn-beijing.aliyuncs.com/OIP.jpg')
)
/

create table "StudentMeta"
(
	"Number" NUMBER(7) not null
		primary key,
	"Name" NVARCHAR2(20) not null,
	"Grade" NUMBER(9) not null,
	"Major" NVARCHAR2(20) not null,
	"Status" NUMBER(1) default 1 not null
)
/

create table "Students"
(
	"StudentId" NUMBER(19) not null
		primary key
		references "Users"
			on delete cascade,
	"Number" NUMBER(7) not null
		references "StudentMeta"
			on delete cascade,
	"Phone" NVARCHAR2(20),
	"Signature" NVARCHAR2(2000),
	"Mail" NVARCHAR2(50),
	"Birthday" DATE
)
/

create table "Clubs"
(
	"ClubId" NUMBER(19) not null
		primary key
		references "Users"
			on delete cascade,
	"Name" NVARCHAR2(100) not null,
	"EstablishmentDate" DATE not null,
	"Type" NUMBER(9) not null,
	"Status" NUMBER(1) default 0 not null,
	"Description" CLOB,
	"Logo" CLOB
)
/

create table "Administrators"
(
	"AdminId" NUMBER(19) not null
		primary key
		references "Users"
			on delete cascade,
	"Name" NVARCHAR2(20) not null,
	"Department" NVARCHAR2(100) not null
)
/

create table "Activities"
(
	"ActivityId" NUMBER(19) generated by default on null as identity
		primary key,
	"ClubId" NUMBER(19) not null
		references "Clubs",
	"AdminId" NUMBER(19)
		references "Administrators",
	"Name" NVARCHAR2(100) not null,
	"Description" NVARCHAR2(2000) not null,
	"Budget" NUMBER(10,2) default 0 not null,
	"Place" NVARCHAR2(100) not null,
	"IsPublic" NUMBER(1) default 0 not null,
	"EventTime" DATE not null,
	"ApplyDate" DATE not null,
	"Status" NUMBER(1) default 0 not null,
	"Suggestion" NVARCHAR2(2000)
)
/

create table "Sponsorships"
(
	"SponsorshipId" NUMBER(19) generated by default on null as identity
		primary key,
	"ClubId" NUMBER(19) not null
		references "Clubs",
	"AdminId" NUMBER(19)
		references "Administrators",
	"Sponsor" NVARCHAR2(100) not null,
	"Amount" NUMBER(10,2) not null,
	"Requirement" NVARCHAR2(2000) not null,
	"ApplyDate" DATE not null,
	"Status" NUMBER(1) default 0 not null,
	"Suggestion" NVARCHAR2(2000)
)
/

create table "Messages"
(
	"MessageId" NUMBER(19) generated by default on null as identity
		primary key,
	"UserId" NUMBER(19) not null
		references "Users"
			on delete cascade,
	"Title" NVARCHAR2(100) not null,
	"Content" NVARCHAR2(2000) not null,
	"Time" DATE not null,
	"Read" NUMBER(1) default 0 not null
)
/

create table "Announcements"
(
	"AnnouncementId" NUMBER(19) generated by default on null as identity
		primary key,
	"UserId" NUMBER(19) not null
		references "Users",
	"Title" NVARCHAR2(100) not null,
	"Content" NVARCHAR2(2000) not null,
	"Time" DATE not null
)
/

create table "Managers"
(
	"ClubId" NUMBER(19) not null
		references "Clubs"
			on delete cascade,
	"StudentId" NUMBER(19) not null
		references "Students"
			on delete cascade,
	"Term" NUMBER(9) not null,
	primary key ("ClubId", "StudentId")
)
/

create table "JoinClub"
(
	"ClubId" NUMBER(19) not null
		references "Clubs"
			on delete cascade,
	"StudentId" NUMBER(19) not null
		references "Students"
			on delete cascade,
	"ApplyDate" DATE not null,
	"ApplyReason" NVARCHAR2(2000),
	"Status" NUMBER(1) default 0 not null,
	primary key ("ClubId", "StudentId")
)
/

create table "ParticipateActivity"
(
	"StudentId" NUMBER(19) not null
		references "Students"
			on delete cascade,
	"ActivityId" NUMBER(19) not null
		references "Activities"
			on delete cascade,
	"ApplyDate" DATE not null,
	"ApplyReason" NVARCHAR2(2000),
	"Status" NUMBER(1) default 0 not null,
	primary key ("StudentId", "ActivityId")
)
/

